import { PDFDocument, rgb, type PDFFont, type PDFPage } from 'pdf-lib';
import fontkit from '@pdf-lib/fontkit';
import koreanFontUrl from '@fontsource/noto-sans-kr/files/noto-sans-kr-korean-400-normal.woff2?url';
import { getTourSnapshot, patchTour } from '../../db/repositories';
import type { Dress, Shop } from '../../types/domain';
import type { ExportOptions, ExportProgress } from '../../types/portable';
import { blobToDataUrl } from '../image/processFace';
import { summarizeDress } from '../dress/options';
import { dressSvgToJpeg } from '../renderer/dressSvg';
import { buildPortableBundle, PORTABLE_FILE_NAME } from './portable';

const A4:[number,number]=[595.28,841.89];
const margin=42;
function wrap(font:PDFFont,text:string,size:number,maxWidth:number){const words=[...text];const lines:string[]=[];let line='';for(const ch of words){const next=line+ch;if(font.widthOfTextAtSize(next,size)>maxWidth&&line){lines.push(line);line=ch}else line=next}if(line)lines.push(line);return lines;}
function drawTextLines(page:PDFPage,font:PDFFont,text:string,x:number,y:number,size=10,maxWidth=500,lineHeight=16,color=rgb(.25,.22,.21)){for(const line of wrap(font,text,size,maxWidth)){page.drawText(line,{x,y,size,font,color});y-=lineHeight}return y;}
function footer(page:PDFPage,font:PDFFont,index:number,total:number){page.drawText(`${index} / ${total}`,{x:500,y:24,size:8,font,color:rgb(.55,.52,.5)});page.drawText('그드레스 · 이 PDF는 웹에서 다시 불러올 수 있습니다.',{x:margin,y:24,size:7,font,color:rgb(.62,.59,.57)});}
function dressLabel(d:Dress,s:Shop){return `${s.name} · ${d.label}`;}
export async function exportPortablePdf(tourId:string,options:ExportOptions,onProgress?:(p:ExportProgress)=>void){
  onProgress?.({step:'prepare',percent:5,label:'데이터 준비'});const snapshot=await getTourSnapshot(tourId);if(!snapshot.dresses.length)throw new Error('드레스를 한 벌 이상 기록해 주세요.');const bundle=buildPortableBundle(snapshot,options.includeFace);const face=bundle.assets[0];const faceData=face?await blobToDataUrl(face.blob):undefined;
  onProgress?.({step:'render',percent:15,label:'드레스 이미지 생성'});const rendered=new Map<string,Uint8Array>();for(let i=0;i<snapshot.dresses.length;i++){rendered.set(snapshot.dresses[i].id,await dressSvgToJpeg(snapshot.dresses[i],faceData,options.includeFace,600,1067));onProgress?.({step:'render',percent:15+Math.round(((i+1)/snapshot.dresses.length)*40),label:`드레스 이미지 ${i+1}/${snapshot.dresses.length}`});await new Promise(r=>setTimeout(r,0));}
  onProgress?.({step:'assemble',percent:60,label:'PDF 조립'});const pdf=await PDFDocument.create();pdf.registerFontkit(fontkit);const fontBytes=await fetch(koreanFontUrl).then(r=>{if(!r.ok)throw new Error('한글 폰트를 불러오지 못했어요.');return r.arrayBuffer()});const font=await pdf.embedFont(fontBytes,{subset:true});pdf.setTitle(`${snapshot.tour.title} - 그드레스`);pdf.setSubject('복원 가능한 드레스투어 기록');pdf.setCreator('그드레스');
  const favorite=snapshot.dresses.filter(d=>d.isFavorite);const totalPages=1+snapshot.dresses.length+(favorite.length?1:0);
  let pageIndex=1;let page=pdf.addPage(A4);page.drawText('그드레스',{x:margin,y:775,size:13,font,color:rgb(.66,.37,.33)});page.drawText(snapshot.tour.title,{x:margin,y:730,size:28,font,color:rgb(.13,.12,.12)});let y=690;y=drawTextLines(page,font,`${snapshot.tour.brideName?`신부 ${snapshot.tour.brideName} · `:''}${snapshot.tour.tourDate||'날짜 미입력'}`,margin,y,11,500,18,rgb(.45,.42,.4));y-=14;page.drawText(`드레스샵 ${snapshot.shops.length}곳`,{x:margin,y,size:12,font});page.drawText(`드레스 ${snapshot.dresses.length}벌`,{x:190,y,size:12,font});page.drawText(`후보 ${favorite.length}벌`,{x:330,y,size:12,font});y-=50;page.drawText('SHOP LIST',{x:margin,y,size:9,font,color:rgb(.66,.37,.33)});y-=26;for(const s of snapshot.shops){const count=snapshot.dresses.filter(d=>d.shopId===s.id).length;page.drawText(`${s.order+1}. ${s.name}`,{x:margin,y,size:12,font});page.drawText(`${count}벌`,{x:470,y,size:10,font,color:rgb(.5,.47,.45)});y-=28;}footer(page,font,pageIndex++,totalPages);
  for(const d of snapshot.dresses){const s=snapshot.shops.find(x=>x.id===d.shopId)!;page=pdf.addPage(A4);page.drawText(dressLabel(d,s),{x:margin,y:790,size:16,font,color:rgb(.18,.16,.15)});if(d.isFavorite)page.drawText('♥ 후보',{x:485,y:790,size:9,font,color:rgb(.72,.36,.32)});const jpg=await pdf.embedJpg(rendered.get(d.id)!);const dims=jpg.scaleToFit(245,435);page.drawImage(jpg,{x:margin,y:320,width:dims.width,height:dims.height});const sx=320;let sy=730;page.drawText('STYLE',{x:sx,y:sy,size:9,font,color:rgb(.66,.37,.33)});sy-=24;sy=drawTextLines(page,font,summarizeDress(d).join(' · ')||'형태 기록 없음',sx,sy,10,230,17);sy-=10;if(d.details.length){page.drawText('DETAIL',{x:sx,y:sy,size:9,font,color:rgb(.66,.37,.33)});sy-=22;sy=drawTextLines(page,font,d.details.join(' · '),sx,sy,9,230,16);sy-=10;}if(d.quickTags.length){page.drawText('평가',{x:sx,y:sy,size:9,font,color:rgb(.66,.37,.33)});sy-=22;sy=drawTextLines(page,font,d.quickTags.join(' · '),sx,sy,9,230,16);sy-=10;}if(d.rating){page.drawText(`별점 ${'★'.repeat(d.rating)}${'☆'.repeat(5-d.rating)}`,{x:sx,y:sy,size:9,font});sy-=26;}page.drawText('MEMO',{x:sx,y:sy,size:9,font,color:rgb(.66,.37,.33)});sy-=22;drawTextLines(page,font,d.memo||'메모 없음',sx,sy,9,230,16,rgb(.38,.35,.33));footer(page,font,pageIndex++,totalPages);}
  if(favorite.length){page=pdf.addPage(A4);page.drawText('MY FAVORITES',{x:margin,y:780,size:11,font,color:rgb(.66,.37,.33)});page.drawText('최종 후보 모아보기',{x:margin,y:740,size:24,font});let fy=690;for(const d of favorite){const s=snapshot.shops.find(x=>x.id===d.shopId)!;page.drawText(`♥ ${s.name} · ${d.label}`,{x:margin,y:fy,size:12,font,color:rgb(.3,.26,.24)});fy-=20;fy=drawTextLines(page,font,summarizeDress(d).slice(0,3).join(' · '),margin+18,fy,8,490,14,rgb(.52,.49,.47));fy-=14;}footer(page,font,pageIndex,totalPages);}
  onProgress?.({step:'attach',percent:92,label:'복원 데이터 첨부'});const jsonBytes=new TextEncoder().encode(JSON.stringify(bundle.payload));await pdf.attach(jsonBytes,PORTABLE_FILE_NAME,{mimeType:'application/json',description:'그드레스 복원 데이터'});for(const asset of bundle.assets){const ref=bundle.payload.assets.find(a=>a.id===asset.id)!;await pdf.attach(new Uint8Array(await asset.blob.arrayBuffer()),ref.fileName,{mimeType:asset.mimeType,description:'로컬 얼굴 이미지'});}const bytes=await pdf.save();await patchTour(tourId,{lastExportedAt:new Date().toISOString()});onProgress?.({step:'done',percent:100,label:'완료'});return new Blob([bytes],{type:'application/pdf'});
}
export function downloadBlob(blob:Blob,fileName:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=fileName;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
