import { db } from './database';
import type { Dress, Id, LocalAsset, Shop, Tour, TourSnapshot } from '../types/domain';
import { DEFAULT_FACE_TRANSFORM } from '../types/domain';
import { normalizeUpper } from '../lib/dress/options';
import { requestPersistentStorage } from '../lib/storage/persist';

const now = () => new Date().toISOString();
const id = () => crypto.randomUUID();
const touchTour = (tourId:string) => db.tours.update(tourId,{updatedAt:now(),lastOpenedAt:now()});

export async function createTour(input:Partial<Pick<Tour,'title'|'brideName'|'tourDate'>> = {}) {
  const t = now(); const name = input.brideName?.trim();
  const tour:Tour = { id:id(), title:input.title?.trim() || `${name || '드레스'} 투어`, brideName:name || undefined, tourDate:input.tourDate, status:'draft', createdAt:t, updatedAt:t, lastOpenedAt:t };
  await db.tours.add(tour); void requestPersistentStorage(); return tour.id;
}
export async function patchTour(tourId:Id, patch:Partial<Tour>) { await db.tours.update(tourId,{...patch,updatedAt:now(),lastOpenedAt:now()}); }
export async function addShop(tourId:Id, input:{name:string; appointmentAt?:string}) {
  const order = await db.shops.where('tourId').equals(tourId).count(); const t=now();
  const shop:Shop={id:id(),tourId,name:input.name.trim(),order,appointmentAt:input.appointmentAt,createdAt:t,updatedAt:t};
  await db.transaction('rw',db.shops,db.tours,async()=>{await db.shops.add(shop);await touchTour(tourId)}); return shop.id;
}
export async function patchShop(shopId:Id, patch:Partial<Shop>) { const shop=await db.shops.get(shopId); if(!shop) return; await db.transaction('rw',db.shops,db.tours,async()=>{await db.shops.update(shopId,{...patch,updatedAt:now()});await touchTour(shop.tourId)}); }
export async function reorderShops(tourId:Id, orderedIds:Id[]) { await db.transaction('rw',db.shops,db.tours,async()=>{for(let i=0;i<orderedIds.length;i++) await db.shops.update(orderedIds[i],{order:i,updatedAt:now()});await touchTour(tourId)}); }
export async function deleteShop(shopId:Id) { const shop=await db.shops.get(shopId); if(!shop)return; await db.transaction('rw',db.shops,db.dresses,db.tours,async()=>{await db.dresses.where('shopId').equals(shopId).delete();await db.shops.delete(shopId);const remaining=await db.shops.where('tourId').equals(shop.tourId).sortBy('order');for(let i=0;i<remaining.length;i++)await db.shops.update(remaining[i].id,{order:i});await touchTour(shop.tourId)}); }
function defaultDress(tourId:string,shopId:string,order:number):Dress { const t=now(); return {id:id(),tourId,shopId,order,label:`Dress ${String(order+1).padStart(2,'0')}`,topStyle:'unknown',neckline:'unknown',silhouette:'unknown',waistline:'unknown',fabric:'unknown',color:'unknown',train:'unknown',details:[],quickTags:[],memo:'',isFavorite:false,createdAt:t,updatedAt:t}; }
export async function addDress(shopId:Id, seed?:Partial<Dress>) { const shop=await db.shops.get(shopId); if(!shop) throw new Error('샵을 찾을 수 없습니다.'); const order=await db.dresses.where('shopId').equals(shopId).count(); const dress={...defaultDress(shop.tourId,shopId,order),...seed,id:id(),order,label:seed?.label || `Dress ${String(order+1).padStart(2,'0')}`,isFavorite:seed?.isFavorite ?? false,createdAt:now(),updatedAt:now()}; await db.transaction('rw',db.dresses,db.tours,async()=>{await db.dresses.add(dress);await touchTour(shop.tourId)}); return dress.id; }
export async function duplicateDress(dressId:Id) { const d=await db.dresses.get(dressId); if(!d)throw new Error('드레스를 찾을 수 없습니다.'); const {id:_,order:__,label:___,createdAt:____,updatedAt:_____,...seed}=d; return addDress(d.shopId,{...seed,isFavorite:false}); }
export async function patchDress(dressId:Id, patch:Partial<Dress>) { const d=await db.dresses.get(dressId); if(!d)return; const next={...patch} as Partial<Dress>; const top=patch.topStyle ?? d.topStyle; const neck=patch.neckline ?? d.neckline; const normalized=normalizeUpper(top,neck); next.neckline=normalized.neckline; if(next.details && next.details.length>4) next.details=next.details.slice(0,4); await db.transaction('rw',db.dresses,db.tours,async()=>{await db.dresses.update(dressId,{...next,updatedAt:now()});await touchTour(d.tourId)}); return normalized.changed; }
export async function reorderDresses(shopId:Id,orderedIds:Id[]){const shop=await db.shops.get(shopId);if(!shop)return;await db.transaction('rw',db.dresses,db.tours,async()=>{for(let i=0;i<orderedIds.length;i++){await db.dresses.update(orderedIds[i],{order:i,label:`Dress ${String(i+1).padStart(2,'0')}`,updatedAt:now()})}await touchTour(shop.tourId)});}
export async function deleteDress(dressId:Id){const d=await db.dresses.get(dressId);if(!d)return;await db.transaction('rw',db.dresses,db.tours,async()=>{await db.dresses.delete(dressId);const rest=await db.dresses.where('shopId').equals(d.shopId).sortBy('order');for(let i=0;i<rest.length;i++)await db.dresses.update(rest[i].id,{order:i,label:`Dress ${String(i+1).padStart(2,'0')}`});await touchTour(d.tourId)});}
export async function setFaceAsset(tourId:Id,asset:Omit<LocalAsset,'id'|'tourId'|'createdAt'>){const old=(await db.tours.get(tourId))?.faceAssetId;const local:LocalAsset={...asset,id:id(),tourId,createdAt:now()};await db.transaction('rw',db.assets,db.tours,db.dresses,async()=>{await db.assets.add(local);await db.tours.update(tourId,{faceAssetId:local.id,updatedAt:now()});if(old)await db.assets.delete(old);const dresses=await db.dresses.where('tourId').equals(tourId).toArray();for(const d of dresses)if(!d.faceTransform)await db.dresses.update(d.id,{faceTransform:DEFAULT_FACE_TRANSFORM});});return local.id;}
export async function removeFaceAsset(tourId:Id){const tour=await db.tours.get(tourId);if(!tour?.faceAssetId)return;await db.transaction('rw',db.assets,db.tours,db.dresses,async()=>{await db.assets.delete(tour.faceAssetId!);await db.tours.update(tourId,{faceAssetId:undefined,updatedAt:now()});const ds=await db.dresses.where('tourId').equals(tourId).toArray();for(const d of ds)await db.dresses.update(d.id,{faceTransform:undefined});});}
export async function getTourSnapshot(tourId:Id):Promise<TourSnapshot>{return db.transaction('r',db.tours,db.shops,db.dresses,db.assets,async()=>{const tour=await db.tours.get(tourId);if(!tour)throw new Error('투어를 찾을 수 없습니다.');const shops=(await db.shops.where('tourId').equals(tourId).toArray()).sort((a,b)=>a.order-b.order);const dresses=(await db.dresses.where('tourId').equals(tourId).toArray()).sort((a,b)=>a.order-b.order);const assets=await db.assets.where('tourId').equals(tourId).toArray();return{tour,shops,dresses,assets}});}
export async function deleteTour(tourId:Id){await db.transaction('rw',db.tours,db.shops,db.dresses,db.assets,async()=>{await db.dresses.where('tourId').equals(tourId).delete();await db.shops.where('tourId').equals(tourId).delete();await db.assets.where('tourId').equals(tourId).delete();await db.tours.delete(tourId)});}
export async function deleteAllData(){await db.transaction('rw',db.tours,db.shops,db.dresses,db.assets,db.meta,async()=>{await Promise.all([db.tours.clear(),db.shops.clear(),db.dresses.clear(),db.assets.clear(),db.meta.clear()])});}
export async function importSnapshot(snapshot:TourSnapshot,strategy:'copy'|'overwrite'){let {tour,shops,dresses,assets}=snapshot;const exists=await db.tours.get(tour.id);if(strategy==='copy'||exists&&strategy!=='overwrite'){const newTourId=id();const assetMap=new Map<string,string>();assets=assets.map(a=>{const nid=id();assetMap.set(a.id,nid);return{...a,id:nid,tourId:newTourId}});const shopMap=new Map<string,string>();shops=shops.map(s=>{const nid=id();shopMap.set(s.id,nid);return{...s,id:nid,tourId:newTourId}});dresses=dresses.map(d=>({...d,id:id(),tourId:newTourId,shopId:shopMap.get(d.shopId)!,faceTransform:d.faceTransform?{...d.faceTransform}:undefined}));tour={...tour,id:newTourId,title:`${tour.title} (복사본)`,faceAssetId:tour.faceAssetId?assetMap.get(tour.faceAssetId):undefined,updatedAt:now(),lastOpenedAt:now()};}else{tour={...tour,updatedAt:now(),lastOpenedAt:now()};}
  await db.transaction('rw',db.tours,db.shops,db.dresses,db.assets,async()=>{if(strategy==='overwrite'&&exists){await db.dresses.where('tourId').equals(tour.id).delete();await db.shops.where('tourId').equals(tour.id).delete();await db.assets.where('tourId').equals(tour.id).delete();await db.tours.delete(tour.id);}await db.tours.add(tour);if(shops.length)await db.shops.bulkAdd(shops);if(dresses.length)await db.dresses.bulkAdd(dresses);if(assets.length)await db.assets.bulkAdd(assets);}); return tour.id;}
