import { useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { ArrowLeft, CheckCircle2, Download, ShieldCheck } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { db } from '../../db/database';
import type { ExportProgress } from '../../types/portable';
import { useUIStore } from '../../stores/uiStore';

export function ExportPage(){const {tourId=''}=useParams();const nav=useNavigate();const toast=useUIStore(s=>s.showToast);const [includeFace,setIncludeFace]=useState(true);const [progress,setProgress]=useState<ExportProgress>();const [blob,setBlob]=useState<Blob>();const [busy,setBusy]=useState(false);const data=useLiveQuery(async()=>{const tour=await db.tours.get(tourId);if(!tour)return undefined;const shopCount=await db.shops.where('tourId').equals(tourId).count();const dresses=await db.dresses.where('tourId').equals(tourId).toArray();return{tour,shopCount,dresses,hasFace:!!tour.faceAssetId}},[tourId]);if(!data)return <main className="p-8 text-center text-sm text-stone-400">내보내기 준비 중...</main>;const filename=`${data.tour.title.replace(/[\\/:*?"<>|]/g,'_')}.pdf`;
return <main className="min-h-dvh px-5 pb-28 pt-[calc(18px+env(safe-area-inset-top))]"><button className="grid h-11 w-11 place-items-center rounded-full bg-stone-50" onClick={()=>nav(-1)}><ArrowLeft/></button><p className="mt-8 text-xs font-semibold text-[#a75e55]">PORTABLE PDF</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em]">PDF 한 파일로<br/>기록을 옮겨요</h1><div className="mt-7 rounded-3xl bg-[#faf7f5] p-5"><div className="font-bold">{data.tour.title}</div><div className="mt-2 text-sm text-stone-400">샵 {data.shopCount} · 드레스 {data.dresses.length} · 후보 {data.dresses.filter(d=>d.isFavorite).length}</div><div className="mt-1 text-xs text-stone-300">예상 {1+data.dresses.length+(data.dresses.some(d=>d.isFavorite)?1:0)}페이지</div></div>{data.hasFace&&<label className="mt-5 flex items-start gap-3 rounded-3xl border border-stone-100 bg-white p-4"><input type="checkbox" className="mt-1 h-5 w-5 accent-[#b96e63]" checked={includeFace} onChange={e=>setIncludeFace(e.target.checked)}/><div><div className="font-semibold">얼굴 사진도 PDF에 포함</div><p className="mt-1 text-xs leading-5 text-stone-400">끄면 보이는 페이지뿐 아니라 PDF 내부 복원 데이터에서도 얼굴 바이트를 완전히 제외합니다.</p></div></label>}<div className="mt-5 flex gap-2 rounded-2xl bg-[#fff2ee] p-4 text-xs leading-5 text-[#8b5750]"><ShieldCheck className="shrink-0" size={18}/><span>PDF 생성은 브라우저 안에서만 진행됩니다. 서버로 사진이나 기록을 보내지 않아요.</span></div>{progress&&<div className="mt-7"><div className="flex items-center justify-between text-sm"><span>{progress.label}</span><span className="text-stone-400">{progress.percent}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-stone-100"><div className="h-full rounded-full bg-[#b96e63] transition-all" style={{width:`${progress.percent}%`}}/></div></div>}{blob&&<div className="mt-6 flex items-center gap-2 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-700"><CheckCircle2 size={18}/>PDF가 준비됐어요.</div>}<div className="fixed bottom-0 left-1/2 w-full max-w-[480px] -translate-x-1/2 border-t border-stone-100 bg-[#fffdfa]/95 px-5 pb-[calc(16px+env(safe-area-inset-bottom))] pt-3 backdrop-blur">{!blob?<button disabled={busy||!data.dresses.length} className="h-14 w-full rounded-2xl bg-stone-900 font-bold text-white disabled:bg-stone-200" onClick={async()=>{setBusy(true);try{const mod=await import('../../lib/pdf/exportPdf');const out=await mod.exportPortablePdf(tourId,{includeFace:includeFace&&data.hasFace},setProgress);setBlob(out)}catch(e){toast(e instanceof Error?e.message:'PDF 생성에 실패했어요.');setProgress(undefined)}finally{setBusy(false)}}}>{busy?'PDF 만드는 중...':'복원 가능한 PDF 만들기'}</button>:<button className="flex h-14 w-full items-center justify-center gap-2 rounded-2xl bg-stone-900 font-bold text-white" onClick={async()=>{const mod=await import('../../lib/pdf/exportPdf');mod.downloadBlob(blob,filename)}}><Download size={18}/>PDF 저장하기</button>}</div></main>}
